# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/65ad4080-8290-492d-b9cd-54284c1df33b";
      fsType = "ext4";
      options = "rw,stripe=32,data=ordered,relatime,discard";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/af2d1e7d-cec8-4077-9097-279a7c5e758c";
      fsType = "ext4";
      options = "data=journal,users,rw,user,auto,exec";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/650f9b63-68e4-45fc-97c7-00e73ec5470d"; }
    ];

  fileSystems."/samba" = {
    device = "//192.168.1.116/Data";
    fsType = "cifs";
    options = "users";
  };

  nix.maxJobs = 8;
}
