# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usbhid" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9bfda93b-b88b-42c7-a8d2-ba3a6a95ce52";
      fsType = "f2fs";
      options = "defaults,noatime,discard,background_gc=off";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/af2d1e7d-cec8-4077-9097-279a7c5e758c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4cecd5bb-d4bb-498a-8712-f790ee7a748a";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9a383600-809c-4ee9-b611-00a150e36533"; }
    ];

  nix.maxJobs = 8;
}
